### PR TITLE
Working with current master

### PR DESCRIPTION
**Pull request by eduardfrigola**
Hi Tim!
Thanks for the addon! Haven't played with it but seems promising!

I got it working with the current master using the new ofAppNoWindow.
~~Only problem now is that the ncurses function getch() conflicts with a custom implemented getch in ofAppNoWindow class: https://github.com/openframeworks/openFrameworks/blob/b674f7ec1f41d8f0fcfea86e3d3d3df3e9bdcf36/libs/openFrameworks/app/ofAppNoWindow.cpp#L53
I will see how can this problem be solved.~~ (double checked and i don't have the error for now)

I also updated the example to work with it.

Thanks!
Eduard.

### CODE REVIEW

**Comment by bernardoaraujor** [comment]
cool, do you have a fork?

**Comment by eduardfrigola** [comment]
Yes! Is the one referenced in this pull request: https://github.com/PlaymodesStudio/ofxNcurses/tree/ofAppNoWindow

**Comment by bernardoaraujor** [comment]
Awesome!
I won't have time to work on this for now, but it's definitely something I want to try out in the near future.

This repo seems to be semi-abandoned :( so please keep your fork public, at least until the PR is merged. That would be much appreciated!

Thanks a lot for your work!

**Comment by tgfrerer** [comment]
hey folks - this looks great, thanks for your contributions :) 

I'll take a look at this this after lunch. Before I merge I want to take a look if everything still works in linux with latest oF master.

**Comment by bernardoaraujor** [comment]
Well there he is! I take the "semi-abandoned" back.
Thanks again for the addon guys!

**Comment by eduardfrigola** [comment]
Works in Raspberry Pi 3B (running sudo apt-get install libcurses5-dev)
Raspbian Stretch
Openframeworks 0.11.0
Also works fine within an SSH session :)

**Comment by tgfrerer** [comment]
Thanks @eduardfrigola, @bernardoaraujor!

I've tested on ubuntu eoan, and it works there too. I've modernised the addon syntax a bit and updated the credits and version info in the readme. 

Let me know if there is any other issue with this addon pops up.

**Comment by eduardfrigola** [comment]
Thanks for getting back to this old project and bring the master repo to life!

**Pull request merged**
